version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 15
  target-branch: dev
  reviewers:
  - @chillibits/android-core-development
  assignees:
  - marcauberer
